CREATE TABLE BD_LIKE (
	LIKE_NUM	NUMBER						--좋아요 PK
	,BOARD_NUM	NUMBER NOT NULL				--게시물 번호 FK
	,MEMBER_NUM	NUMBER						--좋아요 누른 사람 FK
	,CONSTRAINT PK_BD_LIKE PRIMARY KEY(LIKE_NUM)
	,CONSTRAINT FK_BD_LIKE_BOARD_NUM FOREIGN KEY(BOARD_NUM) REFERENCES BD_BOARD(BOARD_NUM) ON DELETE CASCADE 
	,CONSTRAINT FK_BD_LIKE_MEMBER_NUM FOREIGN KEY(MEMBER_NUM) REFERENCES BD_MEMBER(MEMBER_NUM) ON DELETE SET NULL
);
--전체 좋아요 조회
SELECT LIKE_NUM, BOARD_NUM, MEMBER_NUM FROM BD_LIKE;
DROP TABLE BD_LIKE;

--INSERT 좋아요 데이터 추가(좋아요 고유번호, 게시물 고유번호, 좋아요 누른 회원 고유번호)
INSERT INTO BD_LIKE(LIKE_NUM, BOARD_NUM, MEMBER_NUM) VALUES((SELECT NVL(MAX(LIKE_NUM),0)+1 FROM BD_LIKE),1,2)

--SELECTONE 특정 회원(PK), 특정 게시물(PK)에 좋아요 누른 데이터 있는지 조회.
SELECT LIKE_NUM FROM BD_LIKE L 
JOIN BD_MEMBER M ON M.MEMBER_NUM = L.MEMBER_NUM 
JOIN BD_BOARD B ON B.BOARD_NUM =L.BOARD_NUM WHERE M.MEMBER_NUM = 2 AND B.BOARD_NUM = 1

--DELETE 좋아요 데이터 삭제
DELETE FROM BD_LIKE WHERE LIKE_NUM = 1

