CREATE TABLE BD_REPLY (
	REPLY_NUM			NUMBER					--댓글 번호 PK
	,REPLY_CONTENT		VARCHAR2(500) NOT NULL	--댓글 내용
	,MEMBER_NUM			NUMBER					--댓글 작성자 FK
	,REPLY_WRITE_DAY 	DATE DEFAULT SYSDATE 	--댓글 작성일시
	,BOARD_NUM			NUMBER NOT NULL			--댓글 달린 게시물 FK
	,REPLY_PAGE_START 	NUMBER					--페이지네이션 : 댓글 고유번호 시작 번호
	,REPLY_PAGE_END		NUMBER					--페이지네이션 : 댓글 고유번호 끝 번호
	,CONSTRAINT PK_BD_REPLY PRIMARY KEY(REPLY_NUM)
	,CONSTRAINT FK_BD_REPLY_MEMBER_NUM FOREIGN KEY(MEMBER_NUM) REFERENCES BD_MEMBER(MEMBER_NUM) ON DELETE SET NULL
	,CONSTRAINT FK_BD_REPLY_BOARD_NUM FOREIGN KEY(BOARD_NUM) REFERENCES BD_BOARD(BOARD_NUM) ON DELETE CASCADE 
); 




SELECT * FROM BD_REPLY;
DROP TABLE BD_REPLY;

--댓글 추가 : 댓글 PK, 댓글 내용, 작성자(FK), 작성일시, 게시물 번호(FK) 추가 
--댓글작성 버튼 누르면 추가:insert. 댓글pk, 댓글제목, 댓글내용, 댓글작성날짜, 댓글 닉네임
INSERT INTO BD_REPLY(REPLY_NUM, REPLY_CONTENT, MEMBER_NUM, BOARD_NUM)
VALUES((SELECT NVL(MAX(REPLY_NUM),0)+1 FROM BD_REPLY),'안녕하세요.',2, 1);
INSERT INTO BD_REPLY(REPLY_NUM, REPLY_CONTENT, MEMBER_NUM, BOARD_NUM)
VALUES((SELECT NVL(MAX(REPLY_NUM),0)+1 FROM BD_REPLY),'티모 안녕.',1, 1);

--SELECTALL 페이지 범위, 댓글 고유번호, 내용, 닉네임, 프로필경로, 작성일자, 댓글 페이지(시작~끝) 조회
SELECT RN, REPLY_NUM, REPLY_CONTENT, MEMBER_NICKNAME, MEMBER_PROFILE_WAY, REPLY_WRITE_DAY
FROM (SELECT ROW_NUMBER() OVER(ORDER BY REPLY_WRITE_DAY DESC /*작성일자 기준 번호 매기기 위한 Order by*/) AS RN, SR.REPLY_NUM, SR.REPLY_CONTENT, M.MEMBER_NICKNAME, M.MEMBER_PROFILE_WAY, SR.REPLY_WRITE_DAY --RN만들기 위한 서브쿼리 작성
	FROM BD_REPLY SR
	JOIN BD_MEMBER M ON M.MEMBER_NUM = SR.MEMBER_NUM
	WHERE BOARD_NUM = 1
	)
WHERE RN BETWEEN 1 AND 3--게시물 고유번호를 인풋값으로 받으면
ORDER BY REPLY_WRITE_DAY DESC--날짜기준 내림차순 정리해서 조회

--SELECTONE 특정 회원 특정 댓글 조회.
--특정 회원 고유번호 N, 특정 게시물 고유번호 N일 때 댓글 고유번호로 데이터 출력.
SELECT R.REPLY_NUM, B.BOARD_TITLE, R.REPLY_CONTENT, M.MEMBER_NICKNAME, R.REPLY_WRITE_DAY
FROM BD_REPLY R JOIN BD_MEMBER M ON M.MEMBER_NUM = R.MEMBER_NUM
JOIN BD_BOARD B ON B.BOARD_NUM =R.BOARD_NUM WHERE R.MEMBER_NUM = 1 AND R.BOARD_NUM =2

--SELECTONE 댓글 총 개수 카운트 조회
SELECT COUNT(REPLY_NUM) AS REPLY_COUNT 
FROM BD_REPLY 
GROUP BY BOARD_NUM 
HAVING BOARD_NUM=1

-- delete 댓글 삭제 pk값 넘겨오면, 해당댓글 찾아서 모두 삭제
DELETE FROM BD_REPLY WHERE REPLY_NUM = 2

-- update 댓글 수정 pk값 넘겨오면,  댓글내용 수정하기
UPDATE BD_REPLY SET REPLY_CONTENT = '반갑습니다!' WHERE REPLY_NUM = 1

----SELECTALL 특정 회원 댓글 표시 모두 조회.
---- 인풋값 회원 고유번호와 일치할 때, 댓글 고유번호, 게시물 제목, 댓글 내용, 닉네임, 작성일시, 게시물 번호 모두 출력.
--SELECT RN, R.REPLY_NUM, B.BOARD_TITLE, R.REPLY_CONTENT, M.MEMBER_NICKNAME, R.REPLY_WRITE_DAY
--FROM (SELECT ROW_NUMBER() OVER(ORDER BY REPLY_WRITE_DAY DESC) AS RN, R.REPLY_NUM, B.BOARD_TITLE, R.REPLY_CONTENT, M.MEMBER_NICKNAME, R.REPLY_WRITE_DAY
--FROM BD_REPLY R  WHERE bORDER BY BOARD_WRITE_DAY DESC) 
--JOIN BD_MEMBER M ON M.MEMBER_NUM = R.MEMBER_NUM
--JOIN BD_BOARD B ON B.BOARD_NUM =R.BOARD_NUM WHERE M.MEMBER_NUM = 1

--구버전(서브쿼리 사용전)
---- SELECTALL 특정 게시물 댓글목록:게시글 고유번호 fk받아와서 특정 게시물 확인, 해당 게시물의 댓글 모두 출력. 
---- 댓글pk, 댓글내용, 댓글 닉네임, 프로필 이미지, 작성날짜 조회
--SELECT RN, R.REPLY_NUM, R.REPLY_CONTENT, M.MEMBER_NICKNAME, M.MEMBER_PROFILE_WAY, R.REPLY_WRITE_DAY, BRC.REPLY_COUNT
--FROM (SELECT ROW_NUMBER() OVER(ORDER BY R.REPLY_WRITE_DAY DESC) AS RN, R.REPLY_NUM, R.REPLY_CONTENT, M.MEMBER_NICKNAME, M.MEMBER_PROFILE_WAY, R.REPLY_WRITE_DAY, BRC.REPLY_COUNT
--	FROM BD_REPLY R WHERE BOARD_NUM = ? ORDER BY REPLY_WRITE_DAY DESC) RNT
--JOIN BD_MEMBER M ON M.MEMBER_NUM = R.MEMBER_NUM 
--JOIN BD_BOARD B ON B.BOARD_NUM = R.BOARD_NUM
--JOIN (SELECT BOARD_NUM, COUNT(REPLY_NUM) AS REPLY_COUNT FROM BD_REPLY GROUP BY BOARD_NUM) BRC ON BRC.BOARD_NUM = R.BOARD_NUM

