--insert 가게 메뉴정보 추가 : 메뉴 고유번호(PK), 가게 고유번호(FK), 팥/슈프림 붕어빵 판매 여부(Y/N), 야채/김치/만두 판매 여부(Y/N), 미니 붕어빵 판매 여부(Y/N), 고구마 붕어빵 판매 여부(Y/N), 아이스크림/초코 붕어빵 판매 여부(Y/N), 치즈 붕어빵 판매 여부(Y/N), 페스츄리 붕어빵 판매 여부(Y/N), 기타 붕어빵 해당 여부(Y/N)
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 1, 'Y', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'N');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 2, 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 3, 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 4, 'Y', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'N');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 5, 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 6, 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 7, 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 8, 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 9, 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 10, 'Y', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'N');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 11, 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 12, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 13, 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 14, 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 15, 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 16, 'Y', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'N');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 17, 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 18, 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 19, 'Y', 'Y', 'Y', 'N', 'Y', 'Y', 'Y', 'Y');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 20, 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 21, 'N', 'N', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 22, 'Y', 'N', 'Y', 'N', 'Y', 'N', 'Y', 'N');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 23, 'Y', 'Y', 'Y', 'Y', 'N', 'N', 'N', 'N');
INSERT INTO BB_STORE_MENU(STORE_MENU_NUM, STORE_NUM, STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER) 
VALUES ((SELECT NVL(MAX(STORE_MENU_NUM)+1,1) FROM BB_STORE_MENU), 24, 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y', 'Y');

--가게 메뉴 모두 조회
SELECT * FROM BB_STORE_MENU

--selectALL 메뉴별 해당 가게 수 
-- 기본, 야채/김치/만두, 미니, 고구마, 아이스크림/초코, 치즈, 페스츄리, 기타 붕어빵 카테고리별 판매하는 총 매장 수
SELECT STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, 
	STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER, 
	COUNT(STORE_MENU_NUM) AS STOREMENU_COUNT /*STOREMENU_COUNT 별칭 생성*/
FROM BB_STORE_MENU GROUP BY GROUPING /*그룹핑 기준 메뉴 고유번호 총 개수*/
	SETS(STORE_MENU_NOMAL, STORE_MENU_VEG, STORE_MENU_MINI, STORE_MENU_POTATO, 
	STORE_MENU_ICE, STORE_MENU_CHEESE, STORE_MENU_PASTRY, STORE_MENU_OTHER)
	/*Y or N 값에 따라 중복가게 발생. 따라서 Y로만 표현된 데이터 조회하여 중복 가게제거*/
HAVING STORE_MENU_NOMAL = 'Y' OR STORE_MENU_VEG = 'Y' OR STORE_MENU_MINI = 'Y' OR 
	STORE_MENU_POTATO = 'Y' OR STORE_MENU_ICE = 'Y' OR STORE_MENU_CHEESE = 'Y' OR 
	STORE_MENU_PASTRY = 'Y' OR STORE_MENU_OTHER = 'Y'

--selectOne 특정가게 상세정보 조회
SELECT	STORE_MENU_NOMAL, 
		STORE_MENU_VEG,
		STORE_MENU_MINI,
		STORE_MENU_POTATO,
		STORE_MENU_ICE,
		STORE_MENU_CHEESE,
		STORE_MENU_PASTRY,
		STORE_MENU_OTHER
FROM BB_STORE_MENU
WHERE STORE_NUM = 1	
	
--update 특정 가게 판매 메뉴 정보 수정
UPDATE BB_STORE_MENU 
SET STORE_MENU_NOMAL	=	'Y', 	--가게 메뉴 팥/슈크림
	STORE_MENU_VEG		= 	'Y', 	--가게 메뉴 야채/김치/만두 
	STORE_MENU_MINI		= 	'Y',	--가게 메뉴 미니
	STORE_MENU_POTATO	= 	'Y', 	--가게메뉴 고구마
	STORE_MENU_ICE		= 	'Y',	--가게 메뉴 아이스크림/초코
	STORE_MENU_CHEESE	= 	'Y', 	--가게 메뉴 치즈
	STORE_MENU_PASTRY	= 	'Y', 	--가게메뉴 페스츄리
	STORE_MENU_OTHER	= 	'Y' 	-- 가게메뉴 기타
WHERE STORE_NUM = 1 				--가게 고유번호(FK)