--insert 가게 영업정보 추가 : 영업정보 고유번호(PK), 가게 고유번호(FK), 영업요일(MON, TUE, WED, THU, FRI, SAT, SUN), 영업시작시간, 영업종료시간
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '1', 'MON', TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('12:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '1', 'TUE', TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('12:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '1', 'WED', TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('12:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '1', 'THU', TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('12:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '1', 'FRI', TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('12:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '1', 'SAT', TO_DATE('10:00:00', 'HH24:MI:SS'), TO_DATE('19:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '1', 'SUN', TO_DATE('10:00:00', 'HH24:MI:SS'), TO_DATE('19:00:00', 'HH24:MI:SS'));


INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '2', 'MON', TO_DATE('10:00:00', 'HH24:MI:SS'), TO_DATE('19:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '2', 'WED', TO_DATE('10:00:00', 'HH24:MI:SS'), TO_DATE('19:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '2', 'FRI', TO_DATE('10:00:00', 'HH24:MI:SS'), TO_DATE('19:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '2', 'SAT', TO_DATE('10:00:00', 'HH24:MI:SS'), TO_DATE('19:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '2', 'SUN', TO_DATE('10:00:00', 'HH24:MI:SS'), TO_DATE('19:00:00', 'HH24:MI:SS'));

INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '3', 'TUE', TO_DATE('12:30:00', 'HH24:MI:SS'), TO_DATE('22:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '3', 'THU', TO_DATE('12:30:00', 'HH24:MI:SS'), TO_DATE('22:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '3', 'SAT', TO_DATE('12:30:00', 'HH24:MI:SS'), TO_DATE('22:00:00', 'HH24:MI:SS'));

INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '4', 'MON', TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('18:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '4', 'WED', TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('18:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '4', 'FRI', TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('18:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '4', 'SUN', TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('18:00:00', 'HH24:MI:SS'));


INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '5', 'TUE', TO_DATE('10:00:00', 'HH24:MI:SS'), TO_DATE('23:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '6', 'WED', TO_DATE('12:30:00', 'HH24:MI:SS'), TO_DATE('20:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '7', 'MON', TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('12:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '8', 'FRI', TO_DATE('10:00:00', 'HH24:MI:SS'), TO_DATE('19:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '9', 'SUN', TO_DATE('12:30:00', 'HH24:MI:SS'), TO_DATE('22:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '10', 'MON', TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('18:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '11', 'SAT', TO_DATE('10:00:00', 'HH24:MI:SS'), TO_DATE('23:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '12', 'SUN', TO_DATE('12:30:00', 'HH24:MI:SS'), TO_DATE('20:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '13', 'MON', TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('12:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '14', 'THU', TO_DATE('10:00:00', 'HH24:MI:SS'), TO_DATE('19:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '15', 'SUN', TO_DATE('12:30:00', 'HH24:MI:SS'), TO_DATE('22:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '16', 'MON', TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('18:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '17', 'THU', TO_DATE('10:00:00', 'HH24:MI:SS'), TO_DATE('23:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '18', 'SUN', TO_DATE('12:30:00', 'HH24:MI:SS'), TO_DATE('20:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '19', 'MON', TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('12:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '20', 'THU', TO_DATE('10:00:00', 'HH24:MI:SS'), TO_DATE('19:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '21', 'SUN', TO_DATE('12:30:00', 'HH24:MI:SS'), TO_DATE('22:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '22', 'MON', TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('18:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '23', 'THU', TO_DATE('10:00:00', 'HH24:MI:SS'), TO_DATE('23:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '24', 'SUN', TO_DATE('12:30:00', 'HH24:MI:SS'), TO_DATE('20:00:00', 'HH24:MI:SS'));
INSERT INTO BB_STORE_WORK(WORK_NUM, STORE_NUM, STORE_WORK_WEEK, STORE_WORK_OPEN, STORE_WORK_CLOSE) 
VALUES ((SELECT NVL(MAX(WORK_NUM)+1,1) FROM BB_STORE_WORK), '24', 'MON', TO_DATE('09:00:00', 'HH24:MI:SS'), TO_DATE('12:00:00', 'HH24:MI:SS'));

--가게 영업방식 전체 정보 조회
SELECT * FROM BB_STORE_WORK
DELETE BB_STORE_WORK WHERE STORE_NUM BETWEEN 1 AND 36
--가상 테이블 전체 조회
SELECT VIEW_NAME 
FROM USER_VIEWS;

--가상테이블 모두 조회 및 제거
SELECT * FROM BB_VIEW_DELETE_JOIN
DROP VIEW BB_VIEW_DELETE_JOIN



--selectAll 특정가게 영업방식 상세정보 조회
--받은 데이터 : 가게 고유번호
--조회 데이터 : 가게 영업 요일, 영업시작, 종료시간
SELECT STORE_WORK_WEEK, 
TO_CHAR(STORE_WORK_OPEN, 'HH24:MI:SS') AS STORE_OPEN, 
TO_CHAR(STORE_WORK_CLOSE, 'HH24:MI:SS') AS STORE_CLOSED
FROM BB_STORE_WORK WHERE STORE_NUM = 24



--update 가게 영업방식 업데이트(고유번호의 1개의 행 변경)
--받은 데이터 : 가게 고유번호, 영업요일
--업데이트 : 영업요일, 시작, 종료 시간
UPDATE BB_STORE_WORK
SET STORE_WORK_WEEK = 'MON',
    STORE_WORK_OPEN = TO_DATE('10:30', 'HH24:MI:SS'),
    STORE_WORK_CLOSE = TO_DATE('12:30', 'HH24:MI:SS')
WHERE STORE_NUM = 1 AND STORE_WORK_WEEK = 'MON';



--가상테이블(VIEW) 업데이트 수정(기존 데이터 삭제)기능 활용하기 위한 조인문 조회
--조회 데이터 : 가게 고유번호, 영업요일
CREATE VIEW BB_VIEW_DELETE_JOIN AS
SELECT S.STORE_NUM, SW.STORE_WORK_WEEK
FROM BB_STORE S
JOIN BB_STORE_WORK SW ON S.STORE_NUM = SW.STORE_NUM



--delete 영업정보 삭제(update 내 삭제 기능)
DELETE BB_VIEW_DELETE_JOIN 
WHERE STORE_NUM =24
	AND STORE_WORK_WEEK = 'MON' 