--insert 가게 기본정보 추가 : 가게 고유번호(PK), 가게 상호명, 가게 기본주소, 가게 상세주소, 가게 전화번호, 가게폐점여부(Y/N)
INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '1고미진네붕어빵' , '서울 강남구 테헤란로35길25', '1층', '010-3256-2383');
INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '2한지윤네붕어빵' , '서울 강남구 테헤란로146', '본관 앞','010-3760-9870');
INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '3안제호네붕어빵' , '서울 강남구 테헤란로26길', '1층', '010-2733-1425');
INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '4정재희네붕어빵' , '서울 강남구 테헤란로23길', '00가게 앞', '010-1234-4567');
INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '5정재준네붕어빵' , '서울 강남구 테헤란로144', '00건물 옆','010-1234-2222');
INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '6조충현네붕어빵' , '서울 강남구 테헤란로15길', '1층', '010-2735-2422');

INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '7빵가링' , '서울 강남구 테헤란로26길12', '별관 앞', '010-2733-0283');
INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '8우리빵' , '서울 강남구 테헤란로146', '본관 앞','010-3827-3333');
INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '9아리네붕어빵' , '서울 강남구 테헤란로26길', '1층', '02-111-3333');
INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '10붕어빵' , '서울 강남구 테헤란로23길', '00가게 앞', '02-1234-4567');
INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '11붕어빵' , '서울 강남구 테헤란로144', '00건물 옆','010-1234-2222');
INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '12붕어빵' , '서울 강남구 테헤란로20길', '1층', '010-3333-3333');

INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '13집빵' , '서울 강남구 테헤란로26길12', '별관 앞', '010-2733-0283');
INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '14집근처붕어빵' , '서울 강남구 테헤란로146', '본관 앞','010-3827-3333');
INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '15붕어팟' , '서울 강남구 테헤란로26길', '1층', '02-111-3333');
INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '16붕어빵클래스' , '서울 강남구 테헤란로23길', '00가게 앞', '02-1234-4567');
INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '17붕어젝트' , '서울 강남구 테헤란로144', '00건물 옆','010-1234-2222');
INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '18먹붕어' , '서울 강남구 테헤란로20길', '1층', '010-3333-3333');

INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '19여기있붕' , '서울 강남구 테헤란로26길12', '별관 앞', '010-2733-0283');
INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '20붕푸라기' , '서울 강남구 테헤란로146', '본관 앞','010-3827-3333');
INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '21붕어빵어디야' , '서울 강남구 테헤란로26길', '1층', '02-111-3333');
INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '22붕어빵로드맵' , '서울 강남구 테헤란로23길', '00가게 앞', '02-1234-4567');
INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '23붕어빵산만리' , '서울 강남구 테헤란로144', '00건물 옆','010-1234-2222');
INSERT INTO BB_STORE(STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT) 
VALUES ((SELECT NVL(MAX(STORE_NUM)+1,1) FROM BB_STORE), '24바삭바삭' , '서울 강남구 테헤란로20길', '1층', '010-3333-3333');



--가게 테이블 전체 조회
SELECT * FROM BB_STORE
--가게 테이블 고유번호 기준 데이터 삭제
DELETE BB_STORE WHERE STORE_NUM BETWEEN 1 AND 80

--view_selectAll(필터링 가게데이터 전체조회)-----------------------------------------------
CREATE VIEW BB_VIEW_SEARCHSTOREDATA_JOIN AS
SELECT S.STORE_NUM, S.STORE_NAME, S.STORE_ADDRESS, S.STORE_ADDRESS_DETAIL,
S.STORE_CONTACT, S.STORE_CLOSED,
SM.STORE_MENU_NOMAL, SM.STORE_MENU_VEG, SM.STORE_MENU_MINI,
SM.STORE_MENU_POTATO, SM.STORE_MENU_ICE, SM.STORE_MENU_CHEESE,
SM.STORE_MENU_PASTRY, SM.STORE_MENU_OTHER,
SP.STORE_PAYMENT_CASHMONEY, SP.STORE_PAYMENT_CARD, SP.STORE_PAYMENT_ACCOUNT,
SW.STORE_WORK_WEEK, SW.STORE_WORK_OPEN, SW.STORE_WORK_CLOSE
FROM BB_STORE S --가게 테이블 S
--가게S와 가게메뉴SM 테이블의 가게 고유번호가 일치할 때 조인
JOIN BB_STORE_MENU SM ON S.STORE_NUM = SM.STORE_NUM --가게메뉴 테이블 별칭 SM
--가게S와 가게결제방식SP 테이블의 가게 고유번호가 일치할 때 조인
JOIN BB_STORE_PAYMENT SP ON S.STORE_NUM = SP.STORE_NUM	--가게결제방식 테이블 별칭 SP
--가게S와 가게영업정보SM 테이블의 가게 고유번호가 일치할 때 조인
JOIN BB_STORE_WORK SW ON S.STORE_NUM = SW.STORE_NUM	--가게영업정보 테이블 별칭 SW
SELECT * FROM BB_VIEW_SEARCHSTOREDATA_JOIN
DROP VIEW BB_VIEW_SEARCHSTOREDATA_JOIN

--selectAll 예시(필터링 가게PK 조회)-----------------------------------------------------
/*조건값이 이러이러할 때.... PK조회*/
SELECT DISTINCT STORE_NUM
FROM BB_VIEW_SEARCHSTOREDATA_JOIN
WHERE 1=1 /*무조건 첫번째 조건식 성립되도록 형성*/
		AND STORE_NAME LIKE '%붕어빵%'
		AND STORE_CLOSED = 'N'
		AND STORE_MENU_NOMAL = 'Y'
		AND STORE_MENU_VEG = 'N'
		AND STORE_MENU_MINI = 'Y'
		AND STORE_MENU_POTATO = 'N'
		AND STORE_MENU_ICE = 'Y'
		AND STORE_MENU_CHEESE = 'N'
		AND STORE_MENU_PASTRY = 'Y'
		AND STORE_MENU_OTHER = 'N'
		AND STORE_PAYMENT_CASHMONEY = 'N'
		AND STORE_PAYMENT_CARD = 'Y'
		AND STORE_PAYMENT_ACCOUNT = 'N'

--selectAll 예시(필터링 가게정보 데이터 모두 조회)-----------------------------------------------------	
--기능 : 가게 고유번호 역순 정렬 + 페이지네이션
--조회 데이터 : 가게 고유번호(PK), 폐점여부, 상호명, 전화번호, 기본주소, 상세주소	
SELECT * --이하의 FROM절 모두 조회
FROM( --FROM절은 이하 SELECT절 데이터
	SELECT ROW_NUMBER() OVER (
		ORDER BY STORE_NUM DESC)
		AS RN, /* RN별칭 : 고유번호 역순 정렬 */ STORE_NUM, STORE_NAME, STORE_ADDRESS, 
		STORE_ADDRESS_DETAIL, STORE_CONTACT, STORE_CLOSED /* RN + 해당 컬럼명과 함께 조회 */
	FROM(
		SELECT STORE_NUM, STORE_NAME, STORE_ADDRESS, STORE_ADDRESS_DETAIL, STORE_CONTACT, STORE_CLOSED
		FROM BB_STORE
		WHERE STORE_NUM IN( 1, 2, 3, 4, 5, 6, 7) /* WHERE절의 조건들에 해당하는 데이터 출력(인풋값 고유번호 + 역순 정렬) */
		ORDER BY STORE_NUM DESC)
	)SQ /*SQ별칭 : RN + 조건 기반 가게 기본정보 데이터*/
WHERE RN BETWEEN 1 AND 6 /* 페이지네이션 기준(1~6) 데이터 조회*/	


--selectOne 폐점 안한 가게 수 
SELECT COUNT(STORE_NUM) AS STORE_COUNT 
FROM BB_STORE WHERE 1=1 AND STORE_CLOSED = 'N';


--값이 가장 큰 가게고유번호(PK) 조회(+insert 과정에 활용)
--selectOne(가게)
SELECT MAX(STORE_NUM) 
AS MAX_S_NUM	/*별칭 : MAX_S_NUM*/
FROM BB_STORE;


--selectOne 특정 가게 상세정보 조회
--조회 데이터 : 가게 고유번호(PK), 폐점여부, 상호명, 전화번호, 기본주소, 상세주소	
SELECT STORE_NUM,
	STORE_NAME,
	STORE_ADDRESS,
	STORE_ADDRESS_DETAIL,
	STORE_CONTACT,
	STORE_CLOSED
FROM BB_STORE 
WHERE STORE_NUM = 1


--update 가게 기본정보 수정
--변경 가능 데이터 : 가게 상호명, 가게 기본주소, 가게 상세주소, 가게 전화번호, 가게폐점여부(Y/N)
UPDATE BB_STORE
SET STORE_CLOSED = 'N',
STORE_NAME = '티모',
STORE_ADDRESS = '1',
STORE_ADDRESS_DETAIL = '1',
STORE_CONTACT = '1'
WHERE STORE_NUM=1
