--insert 가게 결제방식 추가 : 결제방식 고유번호(PK), 가게 고유번호(FK), 현금결제방식(Y/N), 카드결제방식(Y/N), 계좌이체방식(Y/N)
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '1', 'N', 'Y', 'N');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '2', 'Y', 'Y', 'N');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '3', 'Y', 'N', 'N');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '4', 'N', 'Y', 'N');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '5', 'Y', 'Y', 'Y');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '6', 'Y', 'N', 'Y');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '7', 'N', 'Y', 'N');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '8', 'Y', 'Y', 'N');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '9', 'Y', 'N', 'Y');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '10', 'N', 'Y', 'N');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '11', 'Y', 'Y', 'Y');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '12', 'Y', 'N', 'Y');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '13', 'N', 'Y', 'N');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '14', 'Y', 'Y', 'N');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '15', 'Y', 'N', 'N');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '16', 'N', 'Y', 'N');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '17', 'Y', 'Y', 'Y');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '18', 'Y', 'N', 'Y');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '19', 'N', 'Y', 'N');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '20', 'Y', 'Y', 'N');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '21', 'Y', 'N', 'Y');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '22', 'N', 'Y', 'N');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '23', 'Y', 'Y', 'Y');
INSERT INTO BB_STORE_PAYMENT(STORE_PAYMENT_NUM, STORE_NUM, STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT) 
VALUES ((SELECT NVL(MAX(STORE_PAYMENT_NUM)+1,1) FROM BB_STORE_PAYMENT), '24', 'Y', 'N', 'Y');

--결제방식 전체 조회
SELECT * FROM BB_STORE_PAYMENT

--selectAll 결제방식별 해당하는 매장 총 개수 모두 조회
--조회 데이터 : 현금, 카드, 계좌이체 각 결제방식을 진행하는 매장의 수
SELECT STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT, COUNT(STORE_PAYMENT_NUM) AS STOREPAYMNET_COUNT /*STOREMENU_COUNT 별칭 생성*/
FROM BB_STORE_PAYMENT GROUP BY GROUPING /*그룹핑 기준 메뉴 고유번호 총 개수*/
SETS(STORE_PAYMENT_CASHMONEY, STORE_PAYMENT_CARD, STORE_PAYMENT_ACCOUNT)
/*Y or N 값에 따라 중복가게 발생. 따라서 Y로만 표현된 데이터 조회하여 중복 가게제거*/
HAVING STORE_PAYMENT_CASHMONEY = 'Y' OR STORE_PAYMENT_CARD = 'Y' OR STORE_PAYMENT_ACCOUNT ='Y'

--selectOne 특정 가게 결제방식 상세조회
--받는 데이터 : 가게 고유번호 
--조회 데이터 : 가게 고유번호, 현금, 카드, 계좌이체 사용 여부
SELECT 
STORE_PAYMENT_CASHMONEY,
STORE_PAYMENT_CARD,
STORE_PAYMENT_ACCOUNT
FROM BB_STORE_PAYMENT
WHERE STORE_NUM = ?

--update 특정 가게 결제방식 수정
--받는 데이터 : 가게 고유번호
--수정 데이터 : 현금, 카드, 계좌이체 사용 여부
UPDATE BB_STORE_PAYMENT
SET STORE_PAYMENT_CASHMONEY =?,
STORE_PAYMENT_CARD = ?,
STORE_PAYMENT_ACCOUNT = ?
WHERE STORE_NUM =?
