--create user BUNGEOBBANG identified by 1234;
--제약조건 수정

SELECT * FROM BB_MEMBER;
SELECT * FROM BB_STORE;
SELECT * FROM BB_BOARD_CATEGORY;
SELECT * FROM BB_BOARD;
SELECT * FROM BB_STORE_MENU;
SELECT * FROM BB_STORE_PAYMENT;
SELECT * FROM BB_STORE_WORK;
SELECT * FROM BB_POINT;
SELECT * FROM BB_PAYMENT;
SELECT * FROM BB_DECLARE;
SELECT * FROM BB_IMAGE;
SELECT * FROM BB_LIKE;
SELECT * FROM BB_PRODUCT_CATEGORY;
SELECT * FROM BB_PRODUCT;
SELECT * FROM BB_REPLY;


DROP TABLE BB_MEMBER CASCADE CONSTRAINTS;
DROP TABLE BB_STORE CASCADE CONSTRAINTS;
DROP TABLE BB_BOARD_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE BB_BOARD CASCADE CONSTRAINTS;
DROP TABLE BB_STORE_MENU CASCADE CONSTRAINTS;
DROP TABLE BB_STORE_PAYMENT CASCADE CONSTRAINTS;
DROP TABLE BB_STORE_WORK CASCADE CONSTRAINTS;
DROP TABLE BB_POINT CASCADE CONSTRAINTS;
DROP TABLE BB_PAYMENT CASCADE CONSTRAINTS;
DROP TABLE BB_DECLARE CASCADE CONSTRAINTS;
DROP TABLE BB_IMAGE CASCADE CONSTRAINTS;
DROP TABLE BB_LIKE CASCADE CONSTRAINTS;
DROP TABLE BB_PRODUCT_CATEGORY CASCADE CONSTRAINTS;
DROP TABLE BB_PRODUCT CASCADE CONSTRAINTS;
DROP TABLE BB_REPLY CASCADE CONSTRAINTS;

DELETE FROM BB_STORE_WORK
WHERE STORE_NUM = 24;

---유저테이블
CREATE TABLE BB_MEMBER (
	MEMBER_NUM NUMBER								--PK
	,MEMBER_EMAIL VARCHAR2(200)	NOT NULL --UNIQUE		--이메일(아이디)
	,MEMBER_PASSWORD VARCHAR2(100) NOT NULL			--비밀번호
	,MEMBER_NAME VARCHAR2(30) NOT NULL				--이름
	,MEMBER_NICKNAME VARCHAR2(50) NOT NULL --UNIQUE	--닉네임
	,MEMBER_PHONE VARCHAR2(20) 						--폰번호
	,MEMBER_PROFILE_WAY VARCHAR2(500) NOT NULL		--프로필 이미지 경로
	,MEMBER_ROLE VARCHAR2(30) DEFAULT 'USER' 		--권한/유저구분
	,MEMBER_HIREDAY DATE DEFAULT SYSDATE			--가입일시
	,CONSTRAINT PK_MBNUM PRIMARY KEY(MEMBER_NUM)
	,CHECK (MEMBER_ROLE IN('USER', 'ADMIN', 'ONER'))
);

---붕어빵 가게
CREATE TABLE BB_STORE (
	STORE_NUM NUMBER								--PK
	,STORE_NAME VARCHAR2(100) NOT NULL				--가게 이름
	,STORE_ADDRESS VARCHAR2(500) NOT NULL			--가게 주소
	,STORE_ADDRESS_DETAIL VARCHAR2(100) NOT NULL	--가게 상세 주소
	,STORE_CONTACT VARCHAR2(20)						--연락처
	,STORE_CLOSED CHAR(1) DEFAULT 'N' 				--폐점여부
	,CONSTRAINT PK_STORENUM PRIMARY KEY(STORE_NUM)
	,CHECK (STORE_CLOSED IN('Y', 'N'))
);

---보드 카테고리
CREATE TABLE BB_BOARD_CATEGORY(
	CATEGORY_NUM NUMBER 							--카테고리 종류 고유번호(FK)
	,CATEGORY_NAME VARCHAR2(30) UNIQUE NOT NULL		--카테고리 이름
	,CONSTRAINT PK_CATEGORYNUM PRIMARY KEY(CATEGORY_NUM)
);


--게시물
CREATE TABLE BB_BOARD (
	BOARD_NUM NUMBER								--게시물 고유번호(PK)
	,BOARD_TITLE VARCHAR2(500) NOT NULL				--게시물 제목
	,BOARD_CONTENT VARCHAR2(1000)					--게시물 내용
	,MEMBER_NUM NUMBER								--작성자
	,BOARD_WRITE_DAY DATE DEFAULT SYSDATE			--작성일시
	,BOARD_OPEN	CHAR(1) DEFAULT 'N'					--게시물 공개여부(공개/비공개)--체크
	,CATEGORY_NUM NUMBER							--카테고리(FK)
	,STORE_NUM NUMBER 								--가게 고유번호(FK)
	,BOARD_DELETE CHAR(1) DEFAULT 'N'				--관리자 글 삭제 여부
	,CONSTRAINT PK_BOARDNUM PRIMARY KEY(BOARD_NUM)
	,FOREIGN KEY(MEMBER_NUM) REFERENCES BB_MEMBER(MEMBER_NUM) ON DELETE SET NULL
	,FOREIGN KEY(CATEGORY_NUM) REFERENCES BB_BOARD_CATEGORY(CATEGORY_NUM) ON DELETE CASCADE
	,FOREIGN KEY(STORE_NUM) REFERENCES BB_STORE(STORE_NUM) ON DELETE CASCADE
	,CHECK (BOARD_OPEN IN('Y', 'N'))
	,CHECK (BOARD_DELETE IN('Y', 'N'))
);

---필터용 메뉴
CREATE TABLE BB_STORE_MENU (
	STORE_MENU_NUM NUMBER
	,STORE_NUM NUMBER  NOT NULL
	,STORE_MENU_NOMAL CHAR(1) DEFAULT 'N'					--팥 슈프림
	,STORE_MENU_VEG CHAR(1) DEFAULT 'N'						--야채 김치 만두
	,STORE_MENU_MINI CHAR(1) DEFAULT 'N'					--미니
	,STORE_MENU_POTATO CHAR(1) DEFAULT 'N'					--고구마
	,STORE_MENU_ICE CHAR(1) DEFAULT 'N'						--아이스크림 초코
	,STORE_MENU_CHEESE CHAR(1) DEFAULT 'N'					--치즈
	,STORE_MENU_PASTRY CHAR(1) DEFAULT 'N'					--패스츄리
	,STORE_MENU_OTHER CHAR(1) DEFAULT 'N'					--기타 
	,CONSTRAINT PK_MENUNUM PRIMARY KEY(STORE_MENU_NUM)
	,FOREIGN KEY(STORE_NUM) REFERENCES BB_STORE(STORE_NUM) ON DELETE CASCADE
	,CHECK (STORE_MENU_NOMAL IN('Y', 'N'))
	,CHECK (STORE_MENU_VEG IN('Y', 'N'))
	,CHECK (STORE_MENU_MINI IN('Y', 'N'))
	,CHECK (STORE_MENU_POTATO IN('Y', 'N'))
	,CHECK (STORE_MENU_ICE IN('Y', 'N'))
	,CHECK (STORE_MENU_CHEESE IN('Y', 'N'))
	,CHECK (STORE_MENU_PASTRY IN('Y', 'N'))
	,CHECK (STORE_MENU_OTHER IN('Y', 'N'))
);

---필터용 구매방법
CREATE TABLE BB_STORE_PAYMENT (
	STORE_PAYMENT_NUM NUMBER							--PK
	,STORE_NUM NUMBER NOT NULL							--가게
	,STORE_PAYMENT_CASHMONEY CHAR(1) DEFAULT 'N' 		--현금
	,STORE_PAYMENT_CARD CHAR(1) DEFAULT 'N' 			--카드
	,STORE_PAYMENT_ACCOUNT CHAR(1) DEFAULT 'N' 			--계좌이체
	,CONSTRAINT PK_PAYNUM PRIMARY KEY(STORE_PAYMENT_NUM)
	,FOREIGN KEY(STORE_NUM) REFERENCES BB_STORE(STORE_NUM) ON DELETE CASCADE
	,CHECK (STORE_PAYMENT_CASHMONEY IN('Y', 'N'))
	,CHECK (STORE_PAYMENT_CARD IN('Y', 'N'))
	,CHECK (STORE_PAYMENT_ACCOUNT IN('Y', 'N'))
);


-- 가게영업정보 테이블
CREATE TABLE BB_STORE_WORK (
	WORK_NUM NUMBER                                 --가게영업정보 고유번호(PK)
	,STORE_NUM NUMBER NOT NULL                      --가게 고유번호(FK)
	,STORE_WORK_WEEK CHAR(3) NOT NULL                --영업요일(MON, TUE, WED, THU, FRI, SAT, SUN로 표기)
	,STORE_WORK_OPEN DATE NOT NULL                  --영업시작시간
	,STORE_WORK_CLOSE DATE NOT NULL                 --영업종료시간
	,CONSTRAINT PK_WORKNUM PRIMARY KEY(WORK_NUM)
	,FOREIGN KEY(STORE_NUM) REFERENCES BB_STORE(STORE_NUM) ON DELETE CASCADE
	,CHECK (STORE_WORK_WEEK IN('MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT', 'SUN'))
);

---포인트
CREATE TABLE BB_POINT (
	POINT_NUM NUMBER						--PK
	,MEMBER_NUM NUMBER						--유저
	,POINT_PLUS NUMBER						--포인트 증가
	,POINT_MINUS NUMBER						--포인트 감소
	,POINT_CONTENT VARCHAR2(100)			--내용
	,CONSTRAINT PK_POINTNUM PRIMARY KEY(POINT_NUM)
	,FOREIGN KEY(MEMBER_NUM) REFERENCES BB_MEMBER(MEMBER_NUM) ON DELETE CASCADE
);

---결제테이블
CREATE TABLE BB_PAYMENT (
	PAYMENT_NUM NUMBER								--PK
	,MEMBER_NUM NUMBER								--유저
	,PAYMENT_STATUS VARCHAR(30) DEFAULT 'WAIT'		--결제 구분
	,PAYMENT_AMOUNT NUMBER							--결제 금액
	,PAYMENT_DAY DATE								--결제 일시
	,PAYMENT_USED VARCHAR(30)						--결제 방식(페이)
	,POINT_NUM NUMBER								--포인트 연결
	,CONSTRAINT PK_BB_PAYMENTNUM PRIMARY KEY(PAYMENT_NUM)
	,FOREIGN KEY(MEMBER_NUM) REFERENCES BB_MEMBER(MEMBER_NUM) ON DELETE CASCADE
	,FOREIGN KEY(POINT_NUM) REFERENCES BB_POINT(POINT_NUM) ON DELETE CASCADE
	,CHECK (PAYMENT_STATUS IN('WAIT', 'CONPLETE', 'CANCEL', 'REFUND')) 
);


---신고테이블
CREATE TABLE BB_DECLARE(						--신고테이블
	DECLARE_NUM NUMBER, 						--신고고유번호
	MEMBER_NUM NUMBER,							--신고자
	STORE_NUM NUMBER,							--신고가게
	DECLARE_CATEGORY VARCHAR2(50) NOT NULL,		--신고카테고리
	DECLARE_DAY DATE DEFAULT SYSDATE 			--신고일시
	,CONSTRAINT PK_DECLARENUM PRIMARY KEY(DECLARE_NUM)
	,FOREIGN KEY(MEMBER_NUM) REFERENCES BB_MEMBER(MEMBER_NUM) ON DELETE SET NULL
	,FOREIGN KEY(STORE_NUM) REFERENCES BB_STORE(STORE_NUM)
);

---이미지
CREATE TABLE BB_IMAGE(
	IMAGE_NUM NUMBER,  						--이미지 고유번호(PK)
	IMAGE_WAY VARCHAR2(500) NOT NULL,		--이미지 서버 경로(확정자)
	BOARD_NUM NUMBER NOT NULL				--게시물 번호(FK)
	,CONSTRAINT PK_IMAGENUM PRIMARY KEY(IMAGE_NUM)
	,FOREIGN KEY(BOARD_NUM) REFERENCES BB_BOARD(BOARD_NUM) ON DELETE CASCADE
);

---좋아요
CREATE TABLE BB_LIKE(
	LIKE_NUM NUMBER, 					--좋아요 고유번호(PK)
	BOARD_NUM NUMBER NOT NULL, 			--게시물 고유번호(FK)
	MEMBER_NUM NUMBER 					--좋아요 누른 유저-회원고유번호(FK)
	,CONSTRAINT PK_LIKENUM PRIMARY KEY(LIKE_NUM)
	,FOREIGN KEY(BOARD_NUM) REFERENCES BB_BOARD(BOARD_NUM) ON DELETE CASCADE
	,FOREIGN KEY(MEMBER_NUM) REFERENCES BB_MEMBER(MEMBER_NUM) ON DELETE SET NULL
);

--상품 카테고리
CREATE TABLE BB_PRODUCT_CATEGORY( 
	PRODUCT_CATEGORY_NUM NUMBER							--PK
	,PRODUCT_CATEGORY_NAME VARCHAR2(30) UNIQUE NOT NULL --카테고리 이름
	,CONSTRAINT PK_BB_PRODUCT_CATEGORYNUM PRIMARY KEY(PRODUCT_CATEGORY_NUM)
);


---상품테이블
CREATE TABLE BB_PRODUCT(
	PRODUCT_NUM NUMBER								--엠디 상품 고유번호(PK)
	,PRODUCT_NAME VARCHAR2(100) NOT NULL 			--엠디 상품이름
	,BOARD_NUM NUMBER			 					--엠디 설명
	,PRODUCT_PRICE NUMBER 		 					--엠디 가격
	,PRODUCT_PROFILE_WAY VARCHAR2(500) NOT NULL 	--엠디 썸네일경로
	,PRODUCT_CATEGORY_NUM NUMBER					--종류 카테고리(문구,의류 등)
	,CONSTRAINT PK_PRODUCTNUM PRIMARY KEY(PRODUCT_NUM)
	,FOREIGN KEY(BOARD_NUM) REFERENCES BB_BOARD(BOARD_NUM) ON DELETE SET NULL
	,FOREIGN KEY(PRODUCT_CATEGORY_NUM) REFERENCES BB_PRODUCT_CATEGORY(PRODUCT_CATEGORY_NUM) ON DELETE SET NULL
);

---댓글테이블
CREATE TABLE BB_REPLY(
   REPLY_NUM NUMBER,								--댓글 고유번호(PK)
   REPLY_CONTENT VARCHAR2(500) NOT NULL,			--댓글 내용
   MEMBER_NUM NUMBER,							 	--댓글 작성자
   REPLY_WRITE_DAY DATE DEFAULT SYSDATE,			--댓글 작성일시
   BOARD_NUM NUMBER									--게시글 번호(FK)
   ,CONSTRAINT PK_BB_REPLY PRIMARY KEY(REPLY_NUM)
   ,FOREIGN KEY(MEMBER_NUM) REFERENCES BB_MEMBER(MEMBER_NUM) ON DELETE SET NULL
   ,FOREIGN KEY(BOARD_NUM) REFERENCES BB_BOARD(BOARD_NUM) ON DELETE CASCADE
);